from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent
DATA_DIR = BASE_DIR / "data"
OUTPUT_DIR = BASE_DIR / "output"

DEFAULT_INPUT_FILE = DATA_DIR / "dean_rag_chunks.json"
DEFAULT_OUTPUT_FILE = OUTPUT_DIR / "normalized_chunks_v2.json"

TARGET_WORDS = 300
MIN_WORDS = 120
MAX_WORDS = 450

OVERLAP_UNITS = 1
TIMESTAMP_GAP_THRESHOLD_MS = 90000

SPLIT_ON_SPEAKER_CHANGE = True
INCLUDE_CONTEXT_IN_TEXT = False
MAX_CONTEXT_WORDS = 60